branch-defaults:
  master:
    environment: wafdemo-dev
    group_suffix: null
global:
  application_name: wafdemo
  branch: null
  default_ec2_keyname: jumpbox_key
  default_platform: Docker 1.12.6
  default_region: us-east-1
  profile: eb-cli
  repository: null
  sc: git
